#!/usr/bin/env node
const welcome = require("./src/welcome")
const package = require("./package.json");
const setProgram = require("./src/setProgram")
const run = require("./src/run")
//欢迎语
welcome.start("welcome to hqwcli");

//设置参数 -v
setProgram.start(package);

//设置选项
run()